### ISSUE TITLE
HNC: 'allowCascadingDelete' to 'allowCascadingDeletion' field change in CRD conversion

### ISSUE THREAD

**Issue by yiqigao217** [kubernetes-sigs/multi-tenancy#1035] opened 2020-08-20 17:27 UTC
Part of #868 

I found that if we replace `allowCascadingDelete` field with `allowCascadingDeletion` field directly in v1alpha2 schema, when passing the value of `v1alpha1.allowCascadingDelete` to `v1alpha2.allowCascadingDeletion` in the CRD conversion, the value is missing.

If I keep both `allowCascadingDelete` and `allowCascadingDeletion` fields in v1alpha2 schema, the value can be passed.

I suspect the CRD schema change (with v1alpha2 as storage version) drops the non-existing `allowCascadingDelete` field in etcd immediately before the CRD conversion. That's why only replacing the field directly failed the value passing.

WDYT @adrianludwin

**Comment by adrianludwin** [comment] 2020-08-20 17:58
As in, even _inside_ the conversion webhook, you can't see the value of `v1a1.aCD`? That's not how storage versions are supposed to work AIUI.

**Comment by yiqigao217** [comment] 2020-08-20 18:46
> As in, even _inside_ the conversion webhook, you can't see the value of `v1a1.aCD`? That's not how storage versions are supposed to work AIUI.

Yes, I manually tested replacing `dst.Spec.AllowCascadingDeletion = src.Spec.AllowCascadingDelete` with `dst.Spec.AllowCascadingDeletion = true` in the conversion webhook. After conversion the v1alpha2 HC has `spec.allowCascadingDeletion` in the `k get` yaml.

It means the new field can **get** value from conversion webhook. However, if passing `src.Spec.AllowCascadingDelete`, I got empty spec in v1alpha2 HC after conversion - `spec:{}`.

**Comment by yiqigao217** [comment] 2020-08-20 21:33
Update:
Setting `CRD_OPTIONS ?= "crd:trivialVersions=false"` does work that because it moves validations from `top-level` to `per-version` so that v1alpha1 will have `allowCascadingDelete` field and v1alpha2 has `allowCascadingDeleting` field in each validation.

The only issue is that I need to remove the [work-around patch](https://github.com/kubernetes-sigs/multi-tenancy/blob/master/incubator/hnc/config/crd/patches/webhook_in_hierarchyconfigurations.yaml#L19-L27) for unserving v1alpha1, because otherwise it overwrites the validations per-version. See https://github.com/kubernetes-sigs/controller-tools/issues/462

I will leave v1alpha1 still serving for now to wait for `unservedversion` marker issue.

/cc @adrianludwin

**Comment by adrianludwin** [comment] 2020-08-21 00:54
sgtm. Maybe the CRD controller that removes v1a1 from the stored versions
can also remove it from the list of served versions?

**Comment by yiqigao217** [comment] 2020-09-01 14:06
Update: This change requires `CRD_OPTIONS ?= "crd:trivialVersions=false"` (which is also the right setting if we have multiple CRD versions) to split v1alpha1 and v1alpha2 schema `per-version` instead of a `top-level` schema. Therefore, we can have different fields (`allowCascadingDelete` vs `allowCascadingDeletion`) in each version.

There are 3 limitations here that we have to work around:
* **Singleton validation** (schema validation on `metadata:properties:name`): since there's no metadata schema marker (see https://github.com/kubernetes-sigs/controller-tools/issues/385), we worked around by adding a kustomize patch to the final CRD manifest in the `top-level` when we were still using `crd:trivialVersions=true`. 
* **Unserve v1alpha1**: `kubebuilder:unservedversion` not working - see https://github.com/kubernetes-sigs/controller-tools/issues/462#. We worked around with kustomize patch too.
* **Kustomize patch** `per-version`: Now that we have CRD schema `per-version` (`crd:trivialVersions=false`), there's no way to add the above kustomize patches, because v1alpha1 and v1alpha2 are in the `versions:` list and kustomize patch cannot update a selected array object (see [issue](https://stackoverflow.com/questions/43009349/jsonpatch-path-to-update-array-object-by-object-id/43288678#43288678)).

We can choose one from these 2 options:
1) For singleton validation, change from using schema validation back to using wehbooks. For unserving v1alpha1, flip the `served:true/false` field by the CRD controller that removes v1alpha1 from `storedVersions`.
2) Copy the CRD `base` manifests generated from `controller-gen` into the kustomize patch and manually add singleton schema validation and v1alpha1 unserved in the patch. Thus the `versions` field is patched with a whole list. I will add this issue as a comment in the patch file.

I would prefer Option#2 because:
* It's easier to implement. Since both versions only exist in the API transition, we only need to make sure we copy the CRD `base` manifests each time if there's a CRD change during the transition. We will switch back to the `top-level` singleton schema validation patch (in limitation 1) once we change CRD to `crd:trivialVersions=true` after API transition.
* It still uses schema validation for singleton that we will keep using in the future.

WDYT? @adrianludwin @rjbez17

**Comment by adrianludwin** [comment] 2020-09-01 15:55
I'd rather not ever go back to trivialVersions=true since we'll need to do
this all over again for v1a2->v1beta1.

How about taking the `manifests` makefile out of the default list of
targets so that it doesn't get rebuilt by default? Then you can manually
patch the generated file, including comments like:

# WARNING! controller-tools will try to remove these lines, don't let it!!!

Hopefully we can get kubernetes-sigs/controller-tools#462
<https://github.com/kubernetes-sigs/controller-tools/issues/462> fixed by
then. Maybe ping the owners again and see what the problem is?

**Comment by yiqigao217** [comment] 2020-09-01 16:00
SG on both 1) keep `trivialVersions=false`, 2) manual patch with comment.

Sure will ping the owner.

**Comment by yiqigao217** [comment] 2020-09-01 16:04
> How about taking the `manifests` makefile out of the default list of targets so that it doesn't get rebuilt by default?

Hmm I think having the patch is enough since it patches on (replaces) the CRD `versions` field with manually patched schema already.

**Comment by adrianludwin** [comment] 2020-09-01 16:48
sg

**Closed** 2020-09-29 18:19 UTC
